baseURL = "http://y-ono.work/"
title = "Yusuke Ono"
theme = "vncnt-hugo"

[params]
  author = "Yusuke Ono"
  description = "Yusuke Ono"
  bio = "Belong to the SSAP12. PMP® #1722009, CompTIA Project+ 1020289380, PMS 認13-1-PMS4415号, RISS (Registered No.002407)"
  avatar = "/project-management-professional-pmp.png"
  favicon = "favicon.ico"


  [params.contact]
    email = "y-ono@nswt.co.jp"
    github = "YusukeOno"
    instagram = ""
    twitter = ""
    riss = "002407"
    blog = "y-ono.hatenablog.com"